spring.application.name=A2ZMart

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.datasource.url=jdbc:mysql://localhost:3306/A2ZMart
spring.datasource.username=root
spring.datasource.password=YourDB#1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

project.image=images/

#behind the scenes of DB connection
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=create

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.A2Z.app.jwtCookieName=springBootA2Z



#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG